In [44]:
import pandas as pd
import numpy as np

In [45]:
true = pd.read_csv('True.csv')
fake = pd.read_csv('Fake.csv')

In [46]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [47]:
fake.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23481 entries, 0 to 23480
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    23481 non-null  object
 1   text     23481 non-null  object
 2   subject  23481 non-null  object
 3   date     23481 non-null  object
dtypes: object(4)
memory usage: 733.9+ KB

In [48]:
true['label']=1

In [49]:
fake['label']=0

In [50]:
news = pd.concat([fake,true],axis=0)

In [51]:
news.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [52]:
news.tail()

,title,text,subject,date,label
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [53]:
news.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [54]:
news=news.drop(['title','subject','date'],axis=1)

In [55]:
news.head()

                                                text  label
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0

In [56]:
news.tail()

                                                    text  label
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...      1
21413  LONDON (Reuters) - LexisNexis, a provider of l...      1
21414  MINSK (Reuters) - In the shadow of disused Sov...      1
21415  MOSCOW (Reuters) - Vatican Secretary of State ...      1
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...      1

In [57]:
news=news.sample(frac=1)

In [58]:
news.head()

                                                    text  label
4756   WASHINGTON (Reuters) - The Republican chairman...      1
22145   This is the final episode of Patrick LIVE on ...      0
2351   Donald Trump s join address to Congress last n...      0
5668   WASHINGTON (Reuters) - In an awkward reversal,...      1
1848   Earlier this week, Devin Nunes finally recused...      0

In [59]:
news.reset_index(inplace=True)

In [60]:
news.head()

   index                                               text  label
0   4756  WASHINGTON (Reuters) - The Republican chairman...      1
1  22145   This is the final episode of Patrick LIVE on ...      0
2   2351  Donald Trump s join address to Congress last n...      0
3   5668  WASHINGTON (Reuters) - In an awkward reversal,...      1
4   1848  Earlier this week, Devin Nunes finally recused...      0

In [61]:
news=news.drop(['index'],axis=1)

In [63]:
news.head()

                                                text  label
0  WASHINGTON (Reuters) - The Republican chairman...      1
1   This is the final episode of Patrick LIVE on ...      0
2  Donald Trump s join address to Congress last n...      0
3  WASHINGTON (Reuters) - In an awkward reversal,...      1
4  Earlier this week, Devin Nunes finally recused...      0

In [65]:
import re## regular expression

In [92]:
def wordopt(text):
  #convert to lowercase
  text=text.lower()

  #remove urls
  text=re.sub(r'https?://\S+|www\.\S+','',text)

  #remove html tags
  text=re.sub('<.*?>+','',text)
  #remove punctuations
  text=re.sub(r'[^\w\s]','',text)
  #remove digits
  text=re.sub(r'\d+','',text)
  #remove extra spaces
  text=re.sub(r'\s+',' ',text)
  #remove newline characters
  text=re.sub(r'\n','',text)
  return text

In [93]:
news['text']=news['text'].apply(wordopt)

In [94]:
news['text']

0        washington reuters the republican chairman of ...
1         this is the final episode of patrick live on ...
2        donald trump s join address to congress last n...
3        washington reuters in an awkward reversal the ...
4        earlier this week devin nunes finally recused ...
                               ...
44893    donald trump made became a household name in t...
44894    seattle reuters a us tax overhaul proposed by ...
44895    harare reuters zimbabwe s ruling zanupf party ...
44896    another day another assault on the first amend...
44897    washington reuters winning over bernie sanders...
Name: text, Length: 44898, dtype: object

In [95]:
x = news['text']
y=news['label']

In [96]:
x

0        washington reuters the republican chairman of ...
1         this is the final episode of patrick live on ...
2        donald trump s join address to congress last n...
3        washington reuters in an awkward reversal the ...
4        earlier this week devin nunes finally recused ...
                               ...
44893    donald trump made became a household name in t...
44894    seattle reuters a us tax overhaul proposed by ...
44895    harare reuters zimbabwe s ruling zanupf party ...
44896    another day another assault on the first amend...
44897    washington reuters winning over bernie sanders...
Name: text, Length: 44898, dtype: object

In [97]:
y

0        1
1        0
2        0
3        1
4        0
        ..
44893    0
44894    1
44895    1
44896    0
44897    1
Name: label, Length: 44898, dtype: int64

In [98]:
from sklearn.model_selection import train_test_split

In [99]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [100]:
x_train.shape

(31428,)

In [101]:
x_test.shape

(13470,)

In [102]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [109]:
vector=TfidfVectorizer()

In [127]:
xv_train=vector.fit_transform(x_train)
xv_test=vector.transform(x_test)

In [112]:
xv_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6454343 stored elements and shape (31428, 175332)>

In [113]:
xv_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2764812 stored elements and shape (13470, 109472)>

In [128]:
from sklearn.linear_model import LogisticRegression

In [129]:
LR=LogisticRegression()
LR.fit(xv_train,y_train)

LogisticRegression()

In [130]:
pred_lr=LR.predict(xv_test)

In [131]:
from sklearn.metrics import accuracy_score, classification_report

accuracy = accuracy_score(y_test, pred_lr)
print(f"Accuracy: {accuracy}")

report = classification_report(y_test, pred_lr)
print("Classification Report:")
print(report)

Accuracy: 0.9890126206384559
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      6991
           1       0.99      0.99      0.99      6479

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470

In [133]:
LR.score(xv_test,y_test)

0.9890126206384559

In [134]:
print(classification_report(y_test,pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      6991
           1       0.99      0.99      0.99      6479

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470

In [135]:
from sklearn.tree import DecisionTreeClassifier
DT=DecisionTreeClassifier()
DT.fit(xv_train,y_train)

DecisionTreeClassifier()

In [140]:
pred_dt=DT.predict(xv_test)

In [138]:
DT.score(xv_test,y_test)

0.9958426132145508

In [141]:
print(classification_report(y_test,pred_dt))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6991
           1       1.00      1.00      1.00      6479

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470

In [144]:
from sklearn.ensemble import RandomForestClassifier
RF=RandomForestClassifier()
RF.fit(xv_train,y_train)

RandomForestClassifier()

In [145]:
pred_rfc=RF.predict(xv_test)

In [146]:
RF.score(xv_test,y_test)

0.9890126206384559

In [147]:
print(classification_report(y_test,pred_rfc))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      6991
           1       0.99      0.99      0.99      6479

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470

In [148]:
from sklearn.ensemble import GradientBoostingClassifier
GB=GradientBoostingClassifier()
GB.fit(xv_train,y_train)

GradientBoostingClassifier()

In [149]:
pred_gb=GB.predict(xv_test)

In [150]:
GB.score(xv_test,y_test)

0.9951744617668894

In [151]:
def output_label(n):
  if n ==0:
    return "it is a fake news"
  elif n==1:
    return "it's a true news"

In [164]:
from sklearn.metrics import accuracy_score, classification_report

print("Logistic Regression Performance:")
print(f"Accuracy: {accuracy_score(y_test, pred_lr)}")
print("Classification Report:")
print(classification_report(y_test, pred_lr))

print("\nDecision Tree Classifier Performance:")
print(f"Accuracy: {accuracy_score(y_test, pred_dt)}")
print("Classification Report:")
print(classification_report(y_test, pred_dt))

print("\nRandom Forest Classifier Performance:")
print(f"Accuracy: {accuracy_score(y_test, pred_rfc)}")
print("Classification Report:")
print(classification_report(y_test, pred_rfc))

print("\nGradient Boosting Classifier Performance:")
print(f"Accuracy: {accuracy_score(y_test, pred_gb)}")
print("Classification Report:")
print(classification_report(y_test, pred_gb))

Logistic Regression Performance:
Accuracy: 0.9890126206384559
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      6991
           1       0.99      0.99      0.99      6479

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470


Decision Tree Classifier Performance:
Accuracy: 0.9958426132145508
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6991
           1       1.00      1.00      1.00      6479

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470


Random Forest Classifier Performance:
Accuracy: 0.9890126206384559
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      6991
           1       0.99      0.99      0.99      6479

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470


Gradient Boosting Classifier Performance:
Accuracy: 0.9951744617668894
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      1.00      6991
           1       0.99      1.00      0.99      6479

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470

In [161]:
def manual_testing(news):
  testing_news={'text':[news]}
  new_def_test=pd.DataFrame(testing_news)
  new_def_test["text"]=new_def_test["text"].apply(wordopt)
  new_x_test=new_def_test["text"]
  new_xv_test=vector.transform(new_x_test)
  pred_LR=LR.predict(new_xv_test)
  pred_DT=DT.predict(new_xv_test)
  pred_RFC=RF.predict(new_xv_test)
  pred_GB=GB.predict(new_xv_test)
  return print("\n\nLR Prediction: {} \nDT Prediction: {} \nRFC Prediction: {} \nGB Prediction: {}".format(output_label(pred_LR[0]),
                                                                                                       output_label(pred_DT[0]),
                                                                                                       output_label(pred_RFC[0]),
                                                                                                       output_label(pred_GB[0])))

In [ ]:
news_article = str(input())

manual_testing(news_article)

Reports are coming in that a major policy shift is expected next week, according to sources close to the matter. Details are scarce at this time, but it is believed to involve significant changes to healthcare regulations.


LR Prediction: it is a fake news
DT Prediction: it is a fake news
RFC Prediction: it is a fake news
GB Prediction: it is a fake news